service: tankerozator

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: dev
  httpApi:
    cors: true

functions:
  hello:
    handler: lambda_function.lambda_handler
    events:
      - httpApi:
          path: /tankeroze
          method: post